### ISSUE TITLE
drillScan: Not using act coordinates properly

### ISSUE THREAD

**Issue by davecparker** [davecparker/mars-app#165]
Recent change to fix iPad aspect has shaken out bugs in the layout of drillScan, which are now visible on all devices. For example:

local H = act.height
...
infoConsole.y = H - 2 \* H / 5

does not properly position relative to the act. This is absolute from y = 0 (which is now in a different location on most devices). Display objects in an act should be positioned relative to act.yMin, act.yMax, or act.yCenter (and similar for x), then they will adapt correctly. Since the infoConsole is supposed to be on the bottom of the act, you probably want to position it at y = act.yMax - something. Similar for other objects in there too.

**Comment by arshiahf** [comment]
Fixed

**Comment by davecparker** [comment]
Still not quite right. Your W and H variables are sometimes used as absolute coordinates, sometimes as width/height. You can see one example bug in your info window, which is not sized/positioned correctly for e.g. iPhone 6. Scanning your code, I think there will be other bugs too. A lot of your code looks like it was originally written assuming a coordinate system of (0, 0) - (W, H). There is no easy way to simply redefine your W and H to fix this. You cannot assume either x or y start at 0.

I will post an article to the Mars group trying to explain more about how to use act coordinates.
